
spring:
  profiles:
    active: local

management:
  security:
    enabled: true
server:
  port: 7070

---
profiles: local
spring:
  main:
    banner-mode: log

  devtools:
    restart:
      additional-paths: src/main/resources/static/, src/main/resources/templates/
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/db_lqtest?autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates/
  data:
    jpa:
      repositories:
        enabled: true

---

profiles: prd