
spring:
  profiles:
    active: local

management:
  security:
    enabled: true
server:
  port: 7070

---
profiles: local
spring:
  main:
    banner-mode: log

  devtools:
    restart:
      additional-paths: src/main/resources/static/
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_lqtest?autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

  data:
    jpa:
      repositories:
        enabled: true

---

profiles: prd